### ISSUE TITLE
Regression for 3D Tiles styling in 1.139

### ISSUE THREAD

**Issue by javagl** [CesiumGS/cesium#13346]
The following sandcastle applies a style with an overridden `show` condition:
```javascript
const viewer = new Cesium.Viewer("cesiumContainer");
viewer.clock.currentTime = new Cesium.JulianDate(2457522.154792);

const tileset = await Cesium.Cesium3DTileset.fromUrl(
  "../../SampleData/Cesium3DTiles/PointCloud/PointCloudWithPerPointProperties/tileset.json",
);
viewer.scene.primitives.add(tileset);
viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0.0, -1.0, 50.0));

const style = new Cesium.Cesium3DTileStyle();
style.show = {
  evaluate : function(feature) {
    return true;
  }
};
tileset.style = style;
```

This works in 1.138: 

https://cesium.com/downloads/cesiumjs/releases/1.138/Apps/Sandcastle2/index.html#c=bVJRa9swEP4rwk8OpHKTNZStbhikD2MUGpZ0e9GLKl+aW+VTkE4Obel/n2zX4LQDI91993130mcZR4FFg3AEL64FwVGsIGCs5e8Oy1VmunzliDUSeJVNrhT1CmmsM0/SRO+BeIs1nPb4GS1qutEM+fxicbmYz+VscXH5dd62UGS64YwWAnBS6qNGHrT99uVm25flzrv63ttckRAqk7JI30bXBwupvy5O6MXaIfHKuliNwj/I+zX4Dlh7dwDPmLjv8+Xf4EhlU0Wj+wUDBPLgsUbGBoLUVZW/C0a0F+fqrRsK07EFP0BXSI9rZLP/pekR8nN5PhVns3ZdpHgy9iLws/3g4fhim7act4KOKMPeHRP7tfUEGm1jclp8E7tIhtFRvgPN0cOkZwjhIaUk2Ee4apE3RW8pGBwYpnd7wrNpVnbxsiV/x/rgPIuYfkLyniF5n+aF4iGap6Q2IbQnK4tBUlbYCKyu//OEhLE6hFTZRWs3+AIqW5ZF4p/IrOu8u2vAW/3cUvaz5W0PSinLIqWfVeycfdB+1PEf

It causes an error in 1.139:  

https://cesium.com/downloads/cesiumjs/releases/1.139/Apps/Sandcastle2/index.html#c=bVLBbtswDP0VwScHSOUma1CsdYMB6aEYCixYsu3iiyozDVtZCijKQTv03yfLNRC3A2xTJN8jqUdrZz2LFuEIJG6EhaNYgcfQyN8plleZTv7KWVZogapscl1RZXuO1MbpZ6kDEVjeYgPjKt+DQWVvFUM+v1hcLuZzOVtcXH6d90W6V6cRGA144MhWR4U88Hvz5Xbbp+WOXPOLTN4RhagyKYv4bFRzMBC7qGJEKNYOLa+MC/XJ8Q/yfg2UAmtyByDGiH2fQD55Z6ts2nUY3dRrsCAPhA0ytuClquv8nTQCvjrXbN2Qmp7KcQeqRvu4Rtb7n8o+Qn4uz6fibNZ9F/E8+aiL5xfzQdPTK266dN6TElT6vTtG/N9eIWiVCVF9cSV2wWpGZ/MdKA4EkwEjBEEMWMEU4LqPvXXmLTmDLsMkyaZMNs3K5C07yjdsDo5YhLieuBOGuJPY2RcPQT9HvvY+zmnLYqCUNbYC65v//GJCG+V9zOyCMRt8hSpblkXEj2jGJTV/tEBGvXSQ/Wx53wellGUR3c8sds48KDqp+A8

The error is
```
TypeError: style.show?.getVariables is not a function
    at collectMetadataUsedInPointCloudStyling 
```

I think that's related to the recent metadata changes, so I hope it's OK to tag @mzschwartz5 (I haven't looked at the details, but it might be as simple as a `defined` check at the right place).

**Comment by mzschwartz5** [comment]
Yep, that's mea culpa! Let's see if I can get a quick fix out for 1.140...

**Comment by javagl** [comment]
It doesn't seem to be overly critical. This way of "overriding" the `show` is one of the `@example` snippets in `Cesium3DTilesStyle`, but I also never used it before. It's posibble to just add some
`getVariables: function() { return []; }`
as a workaround 🤷

**Comment by mzschwartz5** [comment]
@javagl Can you take a look at #13349?
